### ISSUE TITLE
Instax Link WIDE Misdentified as Square

### ISSUE THREAD

**Issue by sturmen** [linssenste/instax-link-web#1]
![image](https://github.com/linssenste/instax-link-web/assets/169858/83059a4e-d226-4d80-ae2e-b6289142f8ef)

The battery and film counts are correct, but the model is misidentified.

Windows 11, Chrome 113

**Comment by zaprodk** [comment]
I can reproduce this. I can select wide format before connecting my printer, but after connecting the site locks onto the square format and I cannot change it. Connection to the printer works flawless (Chrome on Mac OS X Big Sur).
Can we attach some logs or dumps to help debug this problem?

**Comment by Yasston** [comment]
I was also able to reproduce. The WIDE has a definition of 1260 x 840 px. In order for the printer to be identified correctly you need to fix a typo in the PrinterSettings.vue file (replace 1240 by 1260) :
![image](https://github.com/linssenste/instax-link-web/assets/33063733/dd789f6d-2cb5-4b8e-8177-0bf9ea457ffa)
Once that is done, the printer will be recognized as WIDE Link.

But the code still doesn't work, it is impossible to print a photo. I am getting a NotificationTimeout error, and even though I augmented every Tiemout value I could find in the code, it just doesn't work. 
```
Error: Notification timeout
    at http://localhost:4000/src/plugins/printer/instax.bluetooth.ts:58:18 {stack: 'Error: Notification timeout
    at http://loc…src/plugins/printer/instax.bluetooth.ts:58:18', message: 'Notification timeout'}
```
Maybe it needs a different chunk size or a different number of packets (currently 812 I believe).  @linssenste : Would you please be able to help us make your code compatible with the WIDE Link model ? What can we do to assist ?

Many thanks !

**Comment by Yasston** [comment]
This could be solved thanks to @javl on the mentionned related issue [here](https://github.com/javl/InstaxBLE/issues/9). In addition to the fix in the `PrinterSettings.vue` file, you should specify a `chunksize` of `900` for the `WIDE` printer in the `instax.ts` file :
![image](https://github.com/linssenste/instax-link-web/assets/33063733/b84af545-8286-42f2-981b-e30ee9a08664)

Either change directly the `1808` value to `900` if you know you'll only be using the `WIDE` printer, or alter the code to test which printer is connected and decide which chunksize to use (it looks like the `mini` and the `WIDE` both use `900` chunksize, the square uses `1808`).

I haven't tried it though with this project (don't want to lose paper :D), but I'm confident it will work with those alterations

**Comment by linssenste** [comment]
Thanks for your issue and and the hints with the chunking on the other printers. I finally got the time to update the code and incorporate the changes to properly support the INSTAX LARGE and MINI. I updated the code (and the UI completely lol) and should now work with all three types.
