### ISSUE TITLE
Missing Icons?

### ISSUE THREAD

**Issue by sturmen** [linssenste/instax-link-web#2]
![image](https://github.com/linssenste/instax-link-web/assets/169858/1c0c1d27-3693-4f46-9ebe-bb7b75f15a79)
![image](https://github.com/linssenste/instax-link-web/assets/169858/32a1d80c-6c0a-471a-9791-7508b6573626)

I can't help but assume these colored shapes should have icons on them, but I don't know what they're supposed to be.

I'm no web developer but I didn't see any obvious errors or missing assets in the Developer Tools.

Windows 11, Chrome 113

**Comment by linssenste** [comment]
Yeah, there were quite a few bugs with the vuetify framework I was using, now it should be fixed though
