### ISSUE TITLE
Different chunk size for Mini Link (900 instead of 1808)

### ISSUE THREAD

**Issue by javl** [linssenste/instax-link-web#3]
I found an error in Instax-BLE and just checked to confirm your website version has the same problem: images are send in 1808 byte chunks, but the Link Mini needs a size of 900. Using 1808 leads to the printer not responding. Should be an easy fix :)

![image](https://github.com/linssenste/instax-link-web/assets/734644/dfd095a0-e56c-40a2-8b55-2ec019ad5b5f)

**Comment by javl** [comment]
To add to this, 'we' just discovered the Wide also uses a size of 900 :)

[See this issue](https://github.com/javl/InstaxBLE/issues/9#issuecomment-1670873669)

**Comment by chicoe** [comment]
even changing the chunk size to 900 I couldn't get the Mini to print... any ideia what other changes in commands are needed from the Square to the Mini?

**Comment by linssenste** [comment]
I changed the code now to support all types of printed, als the mini and the wide. Yeah the issue was not just with the chunking, but also the counting of the chunks, I had an big-endian format (and the square does not care for some reason) but it has to be little endian.
