### ISSUE TITLE
Image can't be generated properly on the mobile version

### ISSUE THREAD

**Issue by yorkchou92** [linssenste/instax-link-web#7]
Hi,

Update: Android seems normal. This problem is only on iOS.

It seems that some images cannot be generated on the mobile version.
This is the demo site:
![photo_2024-08-26_18-21-57](https://github.com/user-attachments/assets/02ebbcec-df19-4415-a605-d0d1222c7178)
I took a random photo with the iPhone's default camera.
![photo_2024-08-26_18-21-58](https://github.com/user-attachments/assets/ea851f9e-d9f0-4918-b56a-259a5c926674)
I only got a frame after clicking download.
![photo_2024-08-26_18-21-59](https://github.com/user-attachments/assets/6c93b469-3d98-43c8-b45e-c6d227ee4fca)
I uploaded the screenshot, adjusted its position, and set the background color.
![photo_2024-08-26_18-22-00](https://github.com/user-attachments/assets/a52fd401-7250-454b-a9d1-192468b0da4f)
However, after downloading, it was just the frame and the background color.
![photo_2024-08-26_18-22-01](https://github.com/user-attachments/assets/b028fa2d-f182-43f0-9e46-da8124e232aa)

**Comment by linssenste** [comment]
Thanks for pointing this out. I'm going to have a look at this issue because it's kind of weird. For me it works on an iPhone with e.g. screenshot but it's not working with regular images as they are in HEIC format. However you demonstrated it with a screenshot. So, I will have a look
